use_frameworks!

platform :ios, '15.0'

target 'KittyImages_Example' do
  pod 'KittyImages', :path => '../'
  pod 'Kingfisher', '7.1.2'

  target 'KittyImages_Tests' do
    inherit! :search_paths

    
  end
end
